# Generated by Django 4.0.4 on 2022-12-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_itemgroup_item_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='item_group_image',
            field=models.ImageField(null=True, upload_to='productimg'),
        ),
    ]
