# Generated by Django 4.0.4 on 2022-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_itemgroup_item_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='item_group_image',
            field=models.ImageField(default='Desktop\x08anner.png', null=True, upload_to='group_img'),
        ),
    ]
