# Generated by Django 4.0.4 on 2022-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_itemgroup_item_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='item_group_image',
            field=models.ImageField(default=1, upload_to='group_img'),
            preserve_default=False,
        ),
    ]
