# Generated by Django 4.0.4 on 2022-12-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_color_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.color'),
        ),
    ]
