# Generated by Django 4.0.4 on 2022-12-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_color_color_name_remove_product_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_tax_type',
            field=models.CharField(choices=[('CGST/SGST', 'CGST/SGST'), ('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('UNREGD', 'UNREGD'), ('COMPOSITE', 'COMPOSITE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill_type',
            field=models.CharField(choices=[('CGST/SGST', 'CGST/SGST'), ('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('UNREGD', 'UNREGD'), ('COMPOSITE', 'COMPOSITE')], max_length=50),
        ),
    ]
